server:
  port: 8773

spring:
  application:
    name: INQUIRY-SERVICE
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update # 새로 추가한 옵션 Entity Class 기반으로 Table 생성
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://teamrev-db.cskul8vj3asp.ap-northeast-2.rds.amazonaws.com:3306/rev_problem?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: teamrev2021

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://34.64.73.179:8761/eureka
  instance:
  #  hostname: 10.178.0.3
  #  hostname: 121.124.72.50
    hostname: 210.101.247.125
